name: PR-Preview

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

jobs:
  pr-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: pr-comment-check
        with:
          trigger: 'PR preview'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo PR preview triggered!'
        if: steps.pr-comment-check.outputs.triggered == 'true'
      - uses: actions/github-script@v3
        if: steps.pr-comment-check.outputs.triggered == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Your preview link is being generated⏳'
            })
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Build static site
        run: yarn install && yarn build
      - name: Create S3 bucket
        run: aws s3 create-bucket --bucket my-bucket --region us-east-1
